# app/config/routes.yaml
home:
    path: /
    controller: Home
    methods: ['GET', 'HEAD', 'POST']

hello:
    path: /hello(?:/)?(?:/{name})?
    controller: Index::sayHello
    methods: ['GET', 'HEAD']

staticExample:
    path: /static/example
    controller: StaticExample
    methods: ['GET', 'HEAD']

setLocale:
    path: /set/locale/{locale}
    controller: SetLocale
    methods: ['GET', 'HEAD']

login:
    path: /login
    controller: Login
    methods: ['GET', 'HEAD', 'POST']

account:
    path: /account
    controller: Account
    methods: ['GET', 'HEAD', 'POST']

accountVerifyEmail:
    path: /account/email/verify/{token}
    controller: Account::verifyEmailChange
    methods: ['GET', 'HEAD']

logout:
    path: /logout
    controller: Logout
    methods: ['GET', 'HEAD']
